{% set name = "pytask-julia" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_julia-{{ version }}.tar.gz
  sha256: bff9a5f10699df2b45618a1fa8a323c6c78f63dc3c4e8dfb8379e908f7227a7a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - click
    - pytask >=0.2
    - python >=3.7

test:
  imports:
    - pytask_julia
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-julia
  summary: A Pytask plugin for Julia
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-julia
  doc_url: https://github.com/pytask-dev/pytask-julia

extra:
  recipe-maintainers:
    - tobiasraabe
