{% set name = "pytask-julia" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_julia-{{ version }}.tar.gz
  sha256: 29df68c27e9a11ff4f27064cdced0f088c3ec3f29b5a3a4f5d422dbf02cec817

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - click
    - pytask >=0.1
    - python >=3.7

test:
  imports:
    - pytask_julia
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-julia
  summary: A Pytask plugin for Julia
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pytask-dev/pytask-julia
  doc_url: https://github.com/pytask-dev/pytask-julia

extra:
  recipe-maintainers:
    - tobiasraabe
